spring:
  profiles:
    active: dev
    
---
spring.profiles: dev
spring.profiles.include: dev-port, dev-h2, dev-mysql
    
---
spring.profiles: dev-port
server:
  port: 8082

---
spring.profiles: dev-debug
debug: true

---
spring:
  profiles: dev-h2
  datasource: 
#    url: jdbc:log4jdbc:h2:mem:test
    primary:  
      url: jdbc:log4jdbc:h2:~/h2/test;AUTO_SERVER=TRUE
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: sa
      password: 
  jpa: 
    database: h2
    hibernate: 
      ddl-auto: update 
  h2:
    console:
      enabled: true
      path: /console

---
spring:  
  profiles: dev-mysql
  datasource:
    secondary:  
      url: jdbc:log4jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: root
      password: mysql
  jpa: 
    database: mysql
    hibernate: 
      ddl-auto: none 